---
title: "Bayesian Workflow book: Resources"
date: 2026-02-26
date-modified: today
date-format: iso
format:
  html:
    number-sections: false
---

## Related books on Bayesian methods and modeling

- Gelman, Carlin, Stern, Dunson, Vehtari and Rubin (2013). *Bayesian Data Analysis*, Third Edition. Chapman and Hall/CRC.
    - [The book web page](https://www.stat.columbia.edu/~gelman/book/).<br>
    - [Electronic edition for non-commercial purposes only](https://users.aalto.fi/~ave/BDA3.pdf).<br>
    - [Buy the book](https://www.crcpress.com/Bayesian-Data-Analysis-Third-Edition/Gelman-Carlin-Stern-Dunson-Vehtari-Rubin/9781439840955).
- McElreath (2020). *Statistical Rethinking*, Second Edition. Chapman and Hall.
    - [The book web page](https://xcelab.net/rm/).
    - [Buy the book](https://www.crcpress.com/Statistical-Rethinking-A-Bayesian-Course-with-Examples-in-R-and-STAN/McElreath/p/book/9780367139919).
- Gelman, Hill and Vehtari (2020). *Regression and other stories*. Cambridge University Press.<br>
    - [The book web page](https://avehtari.github.io/ROS-Examples/).
    - [Electronic edition for non-commercial purposes only](https://users.aalto.fi/~ave/ROS.pdf).<br>
    - [Buy the book](https://www.cambridge.org/fi/academic/subjects/statistics-probability/statistical-theory-and-methods/regression-and-other-stories).
- Gelman and Vehtari (2024). *Active Statistics*. Cambridge University Press.
    - [The book web page](https://avehtari.github.io/ActiveStatistics/).
    - [Electronic edition for non-commercial purposes only](https://users.aalto.fi/~ave/ActiveStatistics.pdf).
    - [Buy the book](https://www.cambridge.org/core/books/active-statistics/4E066112B3F82CA44C81CB4097960808)

## Related case studies

- [Motorcycle](https://users.aalto.fi/~ave/casestudies/Motorcycle/motorcycle.html): Demonstration of benefits of integration in Bayesian inference with Gaussian processes with heteroscedastic noise model and Hilbert basis function and covariance matrix implementations.
- [Disc golf putting](https://users.aalto.fi/~ave/casestudies/disc_putting/disc_putting.html): Extends the ball golf putting model with an additional dimension and a distance-dependent component. Also illustrates the use of distances known only within some interval.
- [Jacobian](https://users.aalto.fi/~ave/casestudies/Jacobian/jacobian.html): Illustration of Laplace method and Jacobian of parameter transformation.
- [Friends](https://users.aalto.fi/~ave/casestudies/Friends/friends.html): model checking and comprison before model interpretation
- [mesquite](https://users.aalto.fi/~ave/casestudies/mesquite/mesquite.html), [bodyfat](https://users.aalto.fi/~ave/casestudies/bodyfat/bodyfat.html), [candy](https://users.aalto.fi/~ave/casestudies/candy/candy.html): Variable selection
- [winequality-red](https://users.aalto.fi/~ave/casestudies/winequality-red/winequality-red.html) ordinal model variable selection

## Cross-validation FAQ

- [CV-FAQ](https://users.aalto.fi/~ave/CV-FAQ.html)

## R programming and visualization with R

- For R programming basics see [Appendix A of Regression and Other Stories](https://avehtari.github.io/ROS-Examples/Regression_and_Other_Stories_Appendix_A.pdf).
- For learning more about R programming we recommend
    - [Garrett Grolemund, Hands-On Programming with R](https://rstudio-education.github.io/hopr/)
- For learning more about basic and advanced plotting using R we recommend
    - [Kieran Healy, Data Visualization - A practical introduction](https://socviz.co/)
    - [Antony Unwin, Graphical Data Analysis with R](http://www.gradaanwr.net/)
- Further ideas for visualization
    - [ggdist: Visualizations of distributions and uncertainty](https://mjskay.github.io/ggdist/)
    - [tidybayes: Bayesian analysis + tidy data + geoms](http://mjskay.github.io/tidybayes/)
    - [Claus O. Wilke, Fundamentals of Data Visualization](https://serialmentor.com/dataviz/)

## Related software

- [Stan](https://mc-stan.org/)
- [CmdStanR](https://mc-stan.org/cmdstanr/)
- [brms](https://paulbuerkner.com/brms/)
- [rstanarm](https://mc-stan.org/rstanarm/)
- [bayesplot](https://mc-stan.org/bayesplot/)
- [loo](https://mc-stan.org/loo/)
- [posterior](https://mc-stan.org/posterior/)
- [priorsense](https://n-kall.github.io/priorsense/)
- [projpred](https://mc-stan.org/projpred/)
- [ggdist](https://mjskay.github.io/ggdist/)
- [ArviZ](https://python.arviz.org/)
